version: "3.8"
services:
  database:
    container_name: parkinson-mysql-api-test
    image: "mysql"
    volumes:
      - api_test_data:/var/lib/mysql
    env_file:
      - ./env/test.env
    ports:
      - "3306:3306"
    networks:
      - api_test

volumes:
  api_test_data:

networks:
  api_test:
    driver: bridge