version: "3.8"
services:
  backend-prod:
    container_name: parkinson-nodejs
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.prod
    env_file:
      - ./env/prod.env
    ports:
      - 3000:3000
    expose:
      - 3000