version: "3.8"
services:
  database:
    container_name: parkinson-mysql-api-dev
    image: "mysql"
    volumes:
      - api_dev_data:/var/lib/mysql
    env_file:
      - ./env/dev.env
    ports:
      - "3306:3306"
    networks:
      - api_dev
  cache-database:
    container_name: parkinson-redis-api-dev
    image: "redis"
    env_file:
      - ./env/dev.env
    ports:
      - "6379:6379"
    networks:
      - api_dev
  backend-api-dev:
    container_name: parkinson-nodejs-dev
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-dev
    volumes:
      - /Users/chaeminlee/Documents/Repository/Parkinson-Diary/ApiServer/parkinson:/app
    env_file:
      - ./env/dev.env
    ports:
      - "8080:8080"
    expose:
      - 8080
    depends_on:
      - database
      - cache-database
    networks:
      - api_dev

volumes:
  api_dev_data:

networks:
  api_dev:
    driver: bridge